### ISSUE TITLE
Load balancing not working

### ISSUE THREAD

**Issue by ghost** [annakz1/ryu#2]
Hello,
I used the script in my topology where i have two nodes acting as web servers and a host h1:
- Node 1 : 192.168.80.11 -> 00:00:00:00:00:11
- Node 2 : 192.168.80.12 -> 00:00:00:00:00:12
- H1 : 192.168.80.149 -> 00:00:00:00:00:01

i changed the script to match the IP and MAC addresses i am using, so the virtual IP is now 192.168.80.9 and the ports are 3 and 4. 

But its unfortunately not working when i use `curl 192.168.80.9` in h1,
all im seeing (in Wireshark) is this :

> 18	51.198797451	00:00:00_00:00:01	00:00:00_00:00:11	ARP  42	Who has 192.168.80.9? Tell 192.168.80.149

> 23	79.872405202	00:00:00_00:00:11	00:00:00_00:00:01	ARP	60	192.168.80.9 is at 00:00:00:00:00:11

> 17	46.078038628	192.168.80.149	192.168.80.9	TCP	74	[TCP Retransmission] [TCP Port numbers reused] 56070 → 80 [SYN] Seq=0 Win=42340 Len=0 MSS=1460 SACK_PERM=1 TSval=2251954242 TSecr=0 WS=512

And nothing is happening in my nodes..

**Comment by Hamatora21** [comment]
@annakz1 help pls ?
